
development:
  adapter: mysql
  encoding: utf8
  database: monthly_dividend_development
  username: root
  password: 

test:
  adapter: mysql
  encoding: utf8
  database: monthly_dividend_test
  username: root
  password: 


production:
  adapter: mysql
  encoding: utf8
  database: monthly_dividend_production
  username: root
  password: 

